name: cvq-vae
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - cudatoolkit=11.3
  - pytorch=1.10.0
  - torchvision=0.11.1
  - pip=23.0.1
  - numpy=1.23.5
  - pip:
    - einops==0.6.0
    - tensorboardX==2.5.1
    - imageio==2.11.1
    - opencv-python==4.5.4.58
    - scikit-image==0.19.3
    - scikit-learn==1.2.1
    - matplotlib==3.6.3
    - lpips==0.1.4